name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Metrics Generate
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_other: yes
          plugin_languages_details: bytes-size,percentage,lines
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_traffic: yes
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_user: alpha018
          plugin_posts_covers: yes
